import './global.css';
import Script from 'next/script';
import { Dancing_Script } from 'next/font/google';
import { NavigationBridge } from '@/components/NavigationBridge';
import { QueryProvider } from '@/components/QueryProvider';
import { WS_BASE_URL } from '@/lib/constants';

const dancingScript = Dancing_Script({
  subsets: ['latin'],
  variable: '--font-dancing',
  display: 'swap',
});

export const metadata = {
  title: 'ChatApp',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={dancingScript.variable} suppressHydrationWarning>
        <Script
          id="mfe-runtime-config"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `window.__WS_URL__ = ${JSON.stringify(WS_BASE_URL)};`,
          }}
        />
        <QueryProvider>
          <NavigationBridge />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
