import './global.css';
import { Dancing_Script } from 'next/font/google';
import { NavigationBridge } from '@/components/NavigationBridge';

const dancingScript = Dancing_Script({
  subsets: ['latin'],
  variable: '--font-dancing',
  display: 'swap',
});

export const metadata = {
  title: 'ChatApp',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={dancingScript.variable}>
        <NavigationBridge />
        {children}
      </body>
    </html>
  );
}
